### ISSUE TITLE
다크모드 모드 지원 끊겼나요?

### ISSUE THREAD

**Issue by SuFl3770** [openNAMU/openNAMU-Skin-ACME#2]
오픈나무 버전 : v3.1.7-stable-02
스킨셋 버전 : 8

다크모드 css는 남이 있는걸 확인은 했는데 스킨 설정 들어가면

오류
사용 중인 스킨은 스킨 설정 기능을 지원하지 않습니다.

뜹니다. 지원이 끊겼나요?

**Comment by SuFl3770** [comment]
+ 추가로 marisa 스킨을 제외한 대부분 스킨이 스킨 설정에 진입이 안됩니다.

**Comment by surplus-dev** [comment]
ACME 다크모드는 곧 다시 추가 예정 입니다. 귀찮아서 조금 지연되고 있습니다

원래 대부분의 스킨은 원래 스킨 설정이 없어서 메인 스킨 설정을 쓰라고 해놓은 겁니다

**Comment by surplus-dev** [comment]
해결완료 v1.1.2
